"use client";
import type { AnalysisReport } from "@/lib/types";
import { VerdictBanner } from "./VerdictBanner";
import { IdentityCards } from "./IdentityCards";
import { AttackHeatmap } from "./AttackHeatmap";
import { FindingsList } from "./FindingsList";
import { ProcessTree } from "./ProcessTree";
import { SectionsView } from "./SectionsView";
import { IOCPanel } from "./IOCPanel";

export function ReportView({
  report,
  onReset,
}: {
  report: AnalysisReport;
  onReset: () => void;
}) {
  return (
    <div className="fade-in">
      <div style={{ display: "flex", alignItems: "baseline", gap: 12, marginTop: 24 }}>
        <h1 style={{ fontSize: 22, margin: 0 }}>Analysis Report</h1>
        <button className="btn btn-ghost small" onClick={onReset}>
          ← New investigation
        </button>
      </div>

      <VerdictBanner report={report} />

      <h2 className="sec">Executive Summary</h2>
      <div className="card">
        <p style={{ margin: 0 }}>{stripMarkdown(report.summary)}</p>
      </div>

      <h2 className="sec">Identity</h2>
      <IdentityCards report={report} />

      <h2 className="sec">MITRE ATT&amp;CK Heatmap</h2>
      <AttackHeatmap attack={report.attack} />

      <h2 className="sec">
        Findings <span className="muted" style={{ textTransform: "none", letterSpacing: 0 }}>— why this verdict (click to expand evidence)</span>
      </h2>
      <FindingsList findings={report.findings} />

      <h2 className="sec">Dynamic Behavior</h2>
      <ProcessTree dynamic={report.dynamic} />

      <h2 className="sec">Sections &amp; Entropy</h2>
      <SectionsView sections={report.sections} />

      <h2 className="sec">Indicators of Compromise</h2>
      <IOCPanel report={report} />

      <h2 className="sec">Threat Intelligence</h2>
      <IntelTable report={report} />

      <footer className="muted small" style={{ marginTop: 40, borderTop: "1px solid var(--line)", paddingTop: 14 }}>
        Generated by ReQuiem v{report.engine_version} · {report.created_at} · Dynamic
        results may be simulated (badged inline). Sample binaries are never auto-distributed.
      </footer>
    </div>
  );
}

function IntelTable({ report }: { report: AnalysisReport }) {
  const yara = report.yara_matches.join(", ") || "—";
  return (
    <div>
      <div className="scroll">
        <table>
          <thead>
            <tr>
              <th>Source</th>
              <th>Status</th>
              <th>Family</th>
              <th>Detail</th>
            </tr>
          </thead>
          <tbody>
            {report.intel.length === 0 ? (
              <tr>
                <td colSpan={4} className="muted">
                  No intel lookups performed (enable on upload).
                </td>
              </tr>
            ) : (
              report.intel.map((r, i) => (
                <tr key={i}>
                  <td>{r.source}</td>
                  <td>{r.known ? "known" : "unknown"}</td>
                  <td>{r.family ?? "—"}</td>
                  <td className="muted">{r.detail ?? ""}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      <p className="muted small" style={{ marginTop: 8 }}>
        YARA matches: {yara}
      </p>
    </div>
  );
}

// The Python summary uses **markdown bold**; render plainly in this context.
function stripMarkdown(s: string): string {
  return s.replace(/\*\*/g, "");
}
