"use client";
import type { AnalysisReport } from "@/lib/types";
import { VerdictBanner } from "./VerdictBanner";
import { IdentityCards } from "./IdentityCards";
import { AttackHeatmap } from "./AttackHeatmap";
import { FindingsList } from "./FindingsList";
import { ProcessTree } from "./ProcessTree";
import { MemoryMap } from "./MemoryMap";
import { HeapTimeline } from "./HeapTimeline";
import { SectionsView } from "./SectionsView";
import { ImportsStrings } from "./ImportsStrings";
import { CfgView } from "./CfgView";
import { IOCPanel } from "./IOCPanel";
import { PdfButton } from "./PdfButton";

export function ReportView({
  report,
  onReset,
}: {
  report: AnalysisReport;
  onReset: () => void;
}) {
  return (
    <div className="fade-in">
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginTop: 24 }}>
        <h1 style={{ fontSize: 22, margin: 0 }}>Analysis Report</h1>
        <button className="btn btn-ghost small" onClick={onReset}>
          ← New investigation
        </button>
        <div style={{ marginLeft: "auto" }}>
          <PdfButton report={report} />
        </div>
      </div>

      <VerdictBanner report={report} />

      <h2 className="sec">Executive Summary</h2>
      <div className="card">
        <p style={{ margin: 0 }}>{stripMarkdown(report.summary)}</p>
      </div>

      <h2 className="sec">Identity</h2>
      <IdentityCards report={report} />

      <h2 className="sec">MITRE ATT&amp;CK Heatmap</h2>
      <AttackHeatmap attack={report.attack} />

      <h2 className="sec">
        Findings <span className="muted" style={{ textTransform: "none", letterSpacing: 0 }}>— why this verdict (click to expand evidence)</span>
      </h2>
      <FindingsList findings={report.findings} />

      <h2 className="sec">Dynamic Behavior</h2>
      <ProcessTree dynamic={report.dynamic} />

      {report.dynamic.memory_map.length > 0 && (
        <>
          <h2 className="sec">Memory Map <span className="muted" style={{ textTransform: "none", letterSpacing: 0 }}>— address-space snapshot</span></h2>
          <MemoryMap regions={report.dynamic.memory_map} />
        </>
      )}

      {report.dynamic.heap_timeline.length > 0 && (
        <>
          <h2 className="sec">Heap Growth <span className="muted" style={{ textTransform: "none", letterSpacing: 0 }}>— committed memory over time</span></h2>
          <HeapTimeline samples={report.dynamic.heap_timeline} />
        </>
      )}

      <h2 className="sec">
        Imports &amp; Strings <span className="muted" style={{ textTransform: "none", letterSpacing: 0 }}>— capability surface</span>
      </h2>
      <ImportsStrings report={report} />

      <h2 className="sec">Sections &amp; Entropy</h2>
      <SectionsView sections={report.sections} />

      {report.disassembly.available && report.disassembly.functions.length > 0 && (
        <>
          <h2 className="sec">Disassembly <span className="muted" style={{ textTransform: "none", letterSpacing: 0 }}>— entry-point control-flow graph</span></h2>
          <CfgView dis={report.disassembly} />
        </>
      )}

      <h2 className="sec">Indicators of Compromise</h2>
      <IOCPanel report={report} />

      <h2 className="sec">Threat Intelligence</h2>
      <IntelTable report={report} />

      <footer className="muted small" style={{ marginTop: 40, borderTop: "1px solid var(--line)", paddingTop: 14 }}>
        Generated by ReQuiem v{report.engine_version} · {report.created_at} · Dynamic
        results may be simulated (badged inline). Sample binaries are never auto-distributed.
      </footer>
    </div>
  );
}

const YARA_SEV_COLOR: Record<string, string> = {
  info: "#5b6472",
  low: "#3b82f6",
  medium: "#eab308",
  high: "#f97316",
  critical: "#ef4444",
};

function IntelTable({ report }: { report: AnalysisReport }) {
  return (
    <div>
      <div className="scroll">
        <table>
          <thead>
            <tr>
              <th>Source</th>
              <th>Status</th>
              <th>Family</th>
              <th>Detail</th>
            </tr>
          </thead>
          <tbody>
            {report.intel.length === 0 ? (
              <tr>
                <td colSpan={4} className="muted">
                  No intel lookups performed (enable on upload).
                </td>
              </tr>
            ) : (
              report.intel.map((r, i) => (
                <tr key={i}>
                  <td>{r.source}</td>
                  <td>{r.known ? "known" : "unknown"}</td>
                  <td>{r.family ?? "—"}</td>
                  <td className="muted">{r.detail ?? ""}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      <div style={{ marginTop: 10 }}>
        <div className="muted small" style={{ marginBottom: 6 }}>
          YARA matches
        </div>
        {report.yara_matches.length === 0 ? (
          <span className="muted small">—</span>
        ) : (
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {report.yara_matches.map((m, i) => {
              const color = YARA_SEV_COLOR[m.severity] ?? "#5b6472";
              return (
                <span
                  key={i}
                  className="badge"
                  title={m.description}
                  style={{ borderColor: color, color }}
                >
                  {m.family ? `${m.family} · ` : ""}
                  {m.rule}
                  {m.malware_type ? ` (${m.malware_type})` : ""}
                </span>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

// The Python summary uses **markdown bold**; render plainly in this context.
function stripMarkdown(s: string): string {
  return s.replace(/\*\*/g, "");
}
